[tool.poetry]
name = "f710-controller"
version = "0.1.0"
description = ""
authors = ["riku-kimura-kccs <riku-kimura@kccs.co.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
